version: "3"
services:
  app:
    build:
      context: docker
    volumes:
      - ".:/var/www/html"
    ports: 
      - "80:80"
    links:
      - db
  db:
    image: mysql:5.7
    command: 
      mysqld 
       --character-set-server=UTF8MB4 
       --collation-server=utf8mb4_unicode_ci 
       --init-connect='SET NAMES UTF8MB4;'
    environment:
      - MYSQL_DATABASE=h2h
      - MYSQL_ROOT_PASSWORD=root
